/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-04-30 10:02:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"style/ico/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("    <link href=\"style/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom styles for this template -->\r\n");
      out.write("    <link href=\"style/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"style/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"style/js/fancybox/jquery.fancybox.css\" rel=\"stylesheet\" />\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>Signin Template for Bootstrap</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("    <link href=\"http://bootstrapk.com/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom styles for this template -->\r\n");
      out.write("    <link href=\"http://bootstrapk.com/examples/signin/signin.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->\r\n");
      out.write("    <!--[if lt IE 9]><script src=\"../../assets/js/ie8-responsive-file-warning.js\"></script><![endif]-->\r\n");
      out.write("    <script src=\"http://bootstrapk.com/assets/js/ie-emulation-modes-warning.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body data-spy=\"scroll\" data-offset=\"0\" data-target=\"#theMenu\">\r\n");
      out.write("  <!-- Menu -->\r\n");
      out.write("\t<nav class=\"menu\" id=\"theMenu\">\r\n");
      out.write("\t\t<div class=\"menu-wrap\">\r\n");
      out.write("\t\t\t<h1 class=\"logo\"><a href=\"index.html#home\">DSGN NYC</a></h1>\r\n");
      out.write("\t\t\t<i class=\"fa fa-times menu-close\"></i>\r\n");
      out.write("\t\t\t<a href=\"#home\" class=\"smoothScroll\">Home</a>\r\n");
      out.write("\t\t\t<a href=\"#about\" class=\"smoothScroll\">About</a>\r\n");
      out.write("\t\t\t<a href=\"#portfolio\" class=\"smoothScroll\">Portfolio</a>\r\n");
      out.write("\t\t\t<a href=\"#services\" class=\"smoothScroll\">Services</a>\r\n");
      out.write("\t\t\t<a href=\"#contact\" class=\"smoothScroll\">Contact</a>\r\n");
      out.write("\t\t\t<a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("\t\t\t<a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("\t\t\t<a href=\"#\"><i class=\"fa fa-dribbble\"></i></a>\r\n");
      out.write("\t\t\t<a href=\"#\"><i class=\"fa fa-envelope\"></i></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Menu button -->\r\n");
      out.write("\t\t<div id=\"menuToggle\"><i class=\"fa fa-bars\"></i></div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("      <form class=\"form-signin\" role=\"form\" name=\"loginform\" action=\"");
      out.print( request.getContextPath());
      out.write("/MemberLoginAction.me\" method=\"post\">\r\n");
      out.write("        <h2 class=\"form-signin-heading\">Please sign in</h2>\r\n");
      out.write("        <label for=\"InputID\">Your ID</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"InputID\" placeholder=\"Enter id\" name=\"userid\">\r\n");
      out.write("\t\t\t\t<label for=\"InputPwd\">Password</label>\r\n");
      out.write("\t\t\t\t<input type=\"password\" class=\"form-control\" id=\"InputPwd\" placeholder=\"Enter pwd\" name=\"pwd\">\r\n");
      out.write("        \r\n");
      out.write("\t\t\t<!-- <a href=\"MemberJoin.me\">íìê°ì</a> -->\r\n");
      out.write("        \r\n");
      out.write("        <button class=\"btn btn-lg btn-danger btn-block\" type=\"submit\">Sign in</button>\r\n");
      out.write("        \r\n");
      out.write("      </form>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->\r\n");
      out.write("    <script src=\"http://bootstrapk.com/assets/js/ie10-viewport-bug-workaround.js\"></script>\r\n");
      out.write(" <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"style/js/classie.js\"></script>\r\n");
      out.write("    <script src=\"style/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"style/js/smoothscroll.js\"></script>\r\n");
      out.write("\t<script src=\"style/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("\t<script src=\"style/js/fancybox/jquery.fancybox.js\"></script>    \r\n");
      out.write("\t<script src=\"style/js/main.js\"></script>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$.stellar({\r\n");
      out.write("\t\t\t\thorizontalScrolling: false,\r\n");
      out.write("\t\t\t\tverticalOffset: 40\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("      $(function() {\r\n");
      out.write("        //    fancybox\r\n");
      out.write("          jQuery(\".fancybox\").fancybox();\r\n");
      out.write("      });\r\n");
      out.write("\t   </script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write(" ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
