/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-04-30 05:44:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.text.SimpleDateFormat;
import com.boram3.yanolja.DAO.*;
import com.boram3.yanolja.DTO.*;

public final class qna_005fboard_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String userid=null;
	if(session.getAttribute("userid")!=null){
		userid=(String)session.getAttribute("userid");
	}
	
	List boardList=(List)request.getAttribute("boardlist");
	int listcount=((Integer)request.getAttribute("listcount")).intValue();
	int nowpage=((Integer)request.getAttribute("page")).intValue();
	int maxpage=((Integer)request.getAttribute("maxpage")).intValue();
	int startpage=((Integer)request.getAttribute("startpage")).intValue();
	int endpage=((Integer)request.getAttribute("endpage")).intValue();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>MVC 게시판</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 게시판 리스트 -->\r\n");
      out.print( userid );
      out.write("님 환영합니다.\r\n");
      out.write("<table width=700 border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t<tr align=\"center\" valign=\"middle\">\r\n");
      out.write("\t\t<td colspan=\"4\">MVC 게시판</td>\r\n");
      out.write("\t\t<td align=right>\r\n");
      out.write("\t\t\t<font size=2>글 개수 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listcount }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</font>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<td align=right>\r\n");
      out.write("\t\t\t<a href=\"./MemberLogOut.me\">[로그아웃]</a>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td align=right>\r\n");
      out.write("\t\t\t<a href=\"./MemberMyPage.me\">[MyPage]</a>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t팀명: <select id=\"teamlist\">\r\n");
      out.write("\t\t\t\t<option value=\"\">[팀선택]</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<tr align=\"center\" valign=\"middle\" bordercolor=\"#333333\">\r\n");
      out.write("\t\t<td style=\"font-family:Tahoma;font-size:8pt;\" width=\"8%\" height=\"26\">\r\n");
      out.write("\t\t\t<div align=\"center\">번호</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td style=\"font-family:Tahoma;font-size:8pt;\" width=\"50%\">\r\n");
      out.write("\t\t\t<div align=\"center\">제목</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td style=\"font-family:Tahoma;font-size:8pt;\" width=\"14%\">\r\n");
      out.write("\t\t\t<div align=\"center\">작성자</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td style=\"font-family:Tahoma;font-size:8pt;\" width=\"17%\">\r\n");
      out.write("\t\t\t<div align=\"center\">날짜</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td style=\"font-family:Tahoma;font-size:8pt;\" width=\"11%\">\r\n");
      out.write("\t\t\t<div align=\"center\">조회수</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t");

		for(int i=0;i<boardList.size();i++){
			BoardBean bl=(BoardBean)boardList.get(i);
	
      out.write("\r\n");
      out.write("\t<tr align=\"center\" valign=\"middle\" bordercolor=\"#333333\"\r\n");
      out.write("\t\tonmouseover=\"this.style.backgroundColor='F8F8F8'\"\r\n");
      out.write("\t\tonmouseout=\"this.style.backgroundColor=''\">\r\n");
      out.write("\t\t<td height=\"23\" style=\"font-family:Tahoma;font-size:10pt;\">\r\n");
      out.write("\t\t\t");
      out.print(bl.getIdx());
      out.write("\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<td style=\"font-family:Tahoma;font-size:10pt;\">\r\n");
      out.write("\t\t\t<div align=\"left\">\r\n");
      out.write("\t\t\t");
if(bl.getDepth()!=0){ 
      out.write("\r\n");
      out.write("\t\t\t\t");
for(int a=0;a<=bl.getDepth()*2;a++){ 
      out.write("\r\n");
      out.write("\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t▶\r\n");
      out.write("\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t▶\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t<a href=\"./BoardDetailAction.bo?num=");
      out.print(bl.getIdx());
      out.write("\">\r\n");
      out.write("\t\t\t\t");
      out.print(bl.getSubject());
      out.write("\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<td style=\"font-family:Tahoma;font-size:10pt;\">\r\n");
      out.write("\t\t\t<div align=\"center\">");
      out.print(bl.getUserid_fk() );
      out.write("</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td style=\"font-family:Tahoma;font-size:10pt;\">\r\n");
      out.write("\t\t\t<div align=\"center\">");
      out.print(bl.getWritedate() );
      out.write("</div>\r\n");
      out.write("\t\t</td>\t\r\n");
      out.write("\t\t<td style=\"font-family:Tahoma;font-size:10pt;\">\r\n");
      out.write("\t\t\t<div align=\"center\">");
      out.print(bl.getCount() );
      out.write("</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("\t<tr align=center height=20>\r\n");
      out.write("\t\t<td colspan=7 style=font-family:Tahoma;font-size:10pt;>\r\n");
      out.write("\t\t\t");
if(nowpage<=1){ 
      out.write("\r\n");
      out.write("\t\t\t[이전]&nbsp;\r\n");
      out.write("\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t<a href=\"./BoardList.bo?page=");
      out.print(nowpage-1 );
      out.write("\">[이전]</a>&nbsp;\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
for(int a=startpage;a<=endpage;a++){
				if(a==nowpage){
      out.write("\r\n");
      out.write("\t\t\t\t[");
      out.print(a );
      out.write("]\r\n");
      out.write("\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"./BoardList.bo?page=");
      out.print(a );
      out.write('"');
      out.write('>');
      out.write('[');
      out.print(a );
      out.write("]</a>\r\n");
      out.write("\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
if(nowpage>=maxpage){ 
      out.write("\r\n");
      out.write("\t\t\t[다음]\r\n");
      out.write("\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t<a href=\"./BoardList.bo?page=");
      out.print(nowpage+1 );
      out.write("\">[다음]</a>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr align=\"right\">\r\n");
      out.write("\t\t<td colspan=\"5\">\r\n");
      out.write("\t\t\t");
if(userid!=null && userid.equals("admin")){
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"./MemberListAction.me\">[회원관리]</a>\r\n");
      out.write("\t\t\t");
}
      out.write("\r\n");
      out.write("\t   \t\t<a href=\"./BoardWrite.bo\">[글쓰기]</a>\r\n");
      out.write("\t   \t\t<a href=\"./GalleryList.ga\">[갤러리]</a>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
